import { useState } from 'react'
import {
  AlertTriangle, CheckCircle, XCircle, Eye, Shield,
  TrendingUp, Clock, Filter, RefreshCw, Zap
} from 'lucide-react'
import { DEMO_ANOMALIES } from '../data/demoData'
import RiskBadge from '../components/RiskBadge'
import StatusBadge from '../components/StatusBadge'

const RULES = [
  { id: 'BRUTE_FORCE_DETECTED',   label: 'Brute Force Detection',      desc: 'Triggers when >10 failed logins in 5 minutes from same IP',    color: 'red' },
  { id: 'OFF_HOURS_ACTIVITY',     label: 'Off-Hours Activity',         desc: 'Flags activity between 10 PM and 6 AM local time',              color: 'orange' },
  { id: 'NEW_DEVICE_DETECTED',    label: 'New Device Login',           desc: 'Detected when user logs in from a previously unseen device',    color: 'yellow' },
  { id: 'CERT_TAMPERING_DETECTED',label: 'Certificate Tampering',      desc: 'SHA-256 hash mismatch detected against blockchain record',      color: 'red' },
  { id: 'IP_CHANGE_DETECTED',     label: 'IP Address Change',          desc: 'User authenticates from a different IP than usual',             color: 'blue' },
  { id: 'DID_VERIFY_FAILURE',     label: 'DID Verification Failure',   desc: 'DID verification failed 3+ times — possible spoofing attempt',  color: 'purple' },
]

const RULE_DOT = {
  red: 'bg-red-500', orange: 'bg-orange-500', yellow: 'bg-yellow-500',
  blue: 'bg-blue-500', purple: 'bg-purple-500',
}

const TYPE_ICONS = {
  'Multiple Failed Logins': '🔐',
  'Unusual Asset Transfer': '📦',
  'New Device Login':       '💻',
  'Certificate Hash Mismatch': '📄',
  'IP Address Change':      '🌐',
  'DID Verification Failure': '🪪',
}

function AnomalyModal({ anomaly, onClose }) {
  return (
    <div className="fixed inset-0 bg-black/70 backdrop-blur-sm z-50 flex items-center justify-center p-4">
      <div className="glass-card w-full max-w-md p-6">
        <div className="flex items-center justify-between mb-5">
          <h3 className="font-semibold text-white flex items-center gap-2">
            <AlertTriangle size={16} className="text-orange-400" /> Anomaly Report
          </h3>
          <button onClick={onClose} className="text-gray-500 hover:text-white"><XCircle size={18} /></button>
        </div>

        {/* Score */}
        <div className="text-center mb-5 py-4 bg-white/3 rounded-xl">
          <div className={`text-4xl font-black ${anomaly.score >= 80 ? 'text-red-400' : anomaly.score >= 60 ? 'text-orange-400' : anomaly.score >= 40 ? 'text-yellow-400' : 'text-emerald-400'}`}>
            {anomaly.score}
          </div>
          <div className="text-xs text-gray-500 mt-1">Anomaly Score / 100</div>
          <div className="mt-2">
            <RiskBadge level={anomaly.riskLevel} />
          </div>
        </div>

        <div className="space-y-2 text-sm">
          {[
            { label: 'Anomaly ID', value: anomaly.id, mono: true },
            { label: 'Type', value: anomaly.type },
            { label: 'User', value: anomaly.user },
            { label: 'Detection Rule', value: anomaly.rule, mono: true },
            { label: 'Device', value: anomaly.device || 'N/A' },
            { label: 'Timestamp', value: new Date(anomaly.timestamp).toLocaleString() },
          ].map(({ label, value, mono }) => (
            <div key={label} className="flex items-center justify-between py-1.5 border-b border-white/5">
              <span className="text-gray-500">{label}</span>
              <span className={`text-gray-200 text-right ${mono ? 'font-mono text-xs' : ''}`}>{value}</span>
            </div>
          ))}
          <div className="flex items-center justify-between py-1.5 border-b border-white/5">
            <span className="text-gray-500">Resolved</span>
            {anomaly.resolved ? <span className="badge-green"><CheckCircle size={10} />Resolved</span> : <span className="badge-red"><Clock size={10} />Open</span>}
          </div>
        </div>

        <div className="mt-4 bg-white/3 rounded-lg p-3">
          <div className="text-xs text-gray-500 mb-1">Details</div>
          <p className="text-sm text-gray-300">{anomaly.details}</p>
        </div>

        <div className="mt-4 text-xs text-gray-600 italic">
          Risk scores are decision-support values generated by the rule-based engine. Manual review is recommended for critical alerts.
        </div>

        <button onClick={onClose} className="btn-primary w-full justify-center mt-4">Close</button>
      </div>
    </div>
  )
}

export default function Anomalies() {
  const [anomalies, setAnomalies] = useState(DEMO_ANOMALIES)
  const [selected, setSelected] = useState(null)
  const [filter, setFilter] = useState('All')
  const [riskFilter, setRiskFilter] = useState('All')
  const [showRules, setShowRules] = useState(false)

  const filtered = anomalies.filter(a => {
    const matchFilter = filter === 'All' || (filter === 'Open' ? !a.resolved : a.resolved)
    const matchRisk = riskFilter === 'All' || a.riskLevel === riskFilter
    return matchFilter && matchRisk
  })

  const resolve = (id) => {
    setAnomalies(prev => prev.map(a => a.id === id ? { ...a, resolved: true } : a))
  }

  const openCount = anomalies.filter(a => !a.resolved).length
  const criticalCount = anomalies.filter(a => a.riskLevel === 'Critical' && !a.resolved).length

  return (
    <div className="space-y-5">
      {/* Header stats */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        {[
          { label: 'Total Anomalies', value: anomalies.length, color: 'text-orange-400' },
          { label: 'Open', value: openCount, color: 'text-red-400' },
          { label: 'Critical', value: criticalCount, color: 'text-red-400' },
          { label: 'Resolved', value: anomalies.filter(a => a.resolved).length, color: 'text-emerald-400' },
        ].map(s => (
          <div key={s.label} className="glass-card p-4 text-center">
            <div className={`text-2xl font-bold ${s.color}`}>{s.value}</div>
            <div className="text-xs text-gray-500 mt-1">{s.label}</div>
          </div>
        ))}
      </div>

      {/* Critical alert */}
      {criticalCount > 0 && (
        <div className="flex items-start gap-3 bg-red-500/10 border border-red-500/30 rounded-xl p-4 animate-pulse">
          <AlertTriangle size={18} className="text-red-400 flex-shrink-0 mt-0.5" />
          <div>
            <div className="text-sm font-semibold text-red-400">{criticalCount} Critical Anomaly{criticalCount > 1 ? 's' : ''} Require Immediate Attention</div>
            <div className="text-xs text-red-300/70 mt-0.5">
              Review and resolve critical security anomalies immediately.
            </div>
          </div>
        </div>
      )}

      {/* Filters */}
      <div className="flex flex-wrap items-center gap-3">
        <div className="flex items-center gap-2">
          <span className="text-xs text-gray-500">Status:</span>
          {['All', 'Open', 'Resolved'].map(f => (
            <button key={f} onClick={() => setFilter(f)}
              className={`text-xs px-3 py-1.5 rounded-lg border transition-all ${filter === f
                ? 'bg-blue-600/20 border-blue-500/40 text-blue-400'
                : 'border-white/10 text-gray-500 hover:text-gray-300'}`}>
              {f}
            </button>
          ))}
        </div>
        <div className="flex items-center gap-2">
          <span className="text-xs text-gray-500">Risk:</span>
          {['All', 'Critical', 'High', 'Medium', 'Low'].map(f => (
            <button key={f} onClick={() => setRiskFilter(f)}
              className={`text-xs px-3 py-1.5 rounded-lg border transition-all ${riskFilter === f
                ? 'bg-orange-600/20 border-orange-500/40 text-orange-400'
                : 'border-white/10 text-gray-500 hover:text-gray-300'}`}>
              {f}
            </button>
          ))}
        </div>
      </div>

      {/* Anomaly list */}
      <div className="space-y-3">
        {filtered.map(anomaly => (
          <div key={anomaly.id}
            className={`glass-card p-4 border transition-all ${
              !anomaly.resolved && anomaly.riskLevel === 'Critical' ? 'border-red-500/30 bg-red-500/3' :
              !anomaly.resolved && anomaly.riskLevel === 'High' ? 'border-orange-500/20' : ''
            }`}>
            <div className="flex items-start justify-between gap-4">
              <div className="flex items-start gap-3">
                <div className={`text-xl flex-shrink-0 mt-0.5`}>
                  {TYPE_ICONS[anomaly.type] || '⚠️'}
                </div>
                <div>
                  <div className="flex items-center gap-2 flex-wrap">
                    <span className="font-semibold text-white text-sm">{anomaly.type}</span>
                    {!anomaly.resolved && anomaly.riskLevel === 'Critical' && (
                      <span className="text-xs bg-red-500/20 text-red-400 border border-red-500/20 px-1.5 py-0.5 rounded animate-pulse">
                        CRITICAL
                      </span>
                    )}
                  </div>
                  <p className="text-xs text-gray-400 mt-1">{anomaly.details}</p>
                  <div className="flex items-center gap-3 mt-2 text-xs text-gray-600">
                    <span>👤 {anomaly.user}</span>
                    <span>🕐 {new Date(anomaly.timestamp).toLocaleString()}</span>
                    <code className="bg-white/5 px-1.5 py-0.5 rounded text-gray-500">{anomaly.rule}</code>
                  </div>
                </div>
              </div>
              <div className="flex flex-col items-end gap-2 flex-shrink-0">
                <RiskBadge score={anomaly.score} level={anomaly.riskLevel} />
                <div className="flex items-center gap-1">
                  <button onClick={() => setSelected(anomaly)}
                    className="p-1.5 text-gray-500 hover:text-blue-400 hover:bg-blue-500/10 rounded transition-colors">
                    <Eye size={14} />
                  </button>
                  {!anomaly.resolved && (
                    <button onClick={() => resolve(anomaly.id)}
                      className="flex items-center gap-1 text-xs bg-emerald-500/10 text-emerald-400 border border-emerald-500/20 px-2.5 py-1 rounded-lg hover:bg-emerald-500/20 transition-all">
                      <CheckCircle size={12} /> Resolve
                    </button>
                  )}
                  {anomaly.resolved && (
                    <span className="text-xs text-emerald-400 flex items-center gap-1">
                      <CheckCircle size={12} /> Resolved
                    </span>
                  )}
                </div>
              </div>
            </div>
          </div>
        ))}
        {filtered.length === 0 && (
          <div className="glass-card text-center py-12 text-gray-500">
            <Shield size={32} className="mx-auto mb-3 opacity-30" />
            No anomalies found for selected filters.
          </div>
        )}
      </div>

      {/* Detection rules */}
      <div className="glass-card p-5">
        <div className="flex items-center justify-between mb-3">
          <h3 className="font-semibold text-white flex items-center gap-2">
            <Zap size={15} className="text-yellow-400" /> Active Detection Rules
          </h3>
          <button onClick={() => setShowRules(!showRules)} className="text-xs text-blue-400 hover:text-blue-300">
            {showRules ? 'Hide' : 'Show All'}
          </button>
        </div>
        {showRules && (
          <div className="grid md:grid-cols-2 gap-3 mt-3">
            {RULES.map(rule => (
              <div key={rule.id} className="flex items-start gap-3 p-3 bg-white/3 rounded-lg border border-white/5">
                <div className={`w-2 h-2 rounded-full mt-1.5 flex-shrink-0 ${RULE_DOT[rule.color] || 'bg-gray-500'}`}></div>
                <div>
                  <div className="text-xs font-semibold text-white">{rule.label}</div>
                  <code className="text-xs text-gray-500">{rule.id}</code>
                  <p className="text-xs text-gray-400 mt-1">{rule.desc}</p>
                </div>
              </div>
            ))}
          </div>
        )}
        <p className="text-xs text-gray-600 mt-3 italic">
          This is a rule-based anomaly engine. The code is structured to allow ML models to replace individual rules in the future.
        </p>
      </div>

      {selected && <AnomalyModal anomaly={selected} onClose={() => setSelected(null)} />}
    </div>
  )
}
